### ISSUE TITLE
Chute settings do not survive saving and loading as subassembly

### ISSUE THREAD

**Issue by DarthPointer** [ChrisViral/RealChute#100]
KSP v1.11.2, RC v1.4.8.2

1. Create any vehicle and set its chutes up. 
2. Save a subassembly with the chutes.
3. Use the subassembly.
4. See its chute settings have been dropped to initialisation default.

**Comment by ChrisViral** [comment]
RC1 is not currently being maintained unfortunately, this isn't going to get looked into as my energy is currently going into RC2.

Closing.
