### ISSUE TITLE
NullRef from RealChute.ProceduralChute.OnStart in VAB (preventing KCT recovery)

### ISSUE THREAD

**Issue by genehwung** [ChrisViral/RealChute#101]
Having the following error when using with Kerbal Construction Time and Scrapyard, after I recovered the ship I attempted to edit the ship from KCT UI, the parachute was not recognized and thus became a new part, checked the logs, the following error appeared:

Related error:

[ERR 13:40:53.508] Module ProceduralChute threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
  at RealChute.ProceduralChute.OnStart (PartModule+StartState state) [0x005b0] in <aa2d15a844824520a0c77b7f968d6700>:0 
  at Part.ModulesOnStart () [0x00120] in <cd473063d3a2482f8d93d388d0c95035>:0 

Full log: [KSP.log and Player.log](https://drive.google.com/drive/folders/1Oq2DuyN3yMIlJfvb27-e-YP-ooZN1Km6?usp=sharing)

I saw some MM patch for RealChute in KCT, so I assume the parachute should be properly "reset", but the issue seems to be caused by this ProceduralParachute.

**Comment by ChrisViral** [comment]
As mentioned in the forums, if you can reproduce this on a clean install and a clean save I'll take a look, otherwise RC1 is not getting any major fixes atm, especially not if they are the produce of an interaction to another mod.

**Comment by ChrisViral** [comment]
Closing as it is a conflicting issue with other mods, as per forum post.
