### ISSUE TITLE
Adding GUI module to all parachutes

### ISSUE THREAD

**Issue by shoe7ess** [ChrisViral/RealChute#106]
I have always had issues with pressure related pre-deployment of chutes from other mods. I used to have a simple MM patch that did just that, basically made every parachute able to toggle the GUI elements (not sure when this stopped working, I tend to jump around between versions).

I have attempted changing a simple catch-all MM with @MODULE[RealChuteModule] (which worked in the past), but had no success, and eventually duplicated the stock MM patch for each individual part (mostly just Novapunch and BDB chutes), fixed my mistakes with the texture sets but I could only ever get a tiny GUI open from the PAW of the parachute parts that wasn't legible in or out of the action group menu. I guess I'm _asking_: I want to write compatibility patches for non stock/Realchute parachutes (and share it if I can get it working), but I don't know what steps I'm missing. I will continue to test and figure it out on my own, and if I find a decent MM compat script I will leave it here :)

**Comment by ChrisViral** [comment]
Unfortunately it's not that simple and requires some amount of setup on the parts and/or with creating proper libraries. Best ask mod-owners to make their own RC patches, because a generic RC patch is not possible.
