### ISSUE TITLE
Just on the off chance

### ISSUE THREAD

**Issue by NathanKell** [ChrisViral/RealChute#66]
Do you do scaling similar to how TweakScale does? If so, https://github.com/pellinor0/TweakScale/issues/3 -- you may be running into that.

**Comment by StupidChris** [comment]
I'll take a deeper look, but I do believe I use part.transform and didnt set the hasChanged flag

**Comment by ChrisViral** [comment]
Don't believe this issue occurs with RealChute, closing for now, would rather not mess with the scale code and risk breaking something without clear indication of issues
