### ISSUE TITLE
Feature request: make safety state accessible to kOS

### ISSUE THREAD

**Issue by latenightgames** [ChrisViral/RealChute#69]
Hey,

Just a quick feature request; I don't know how quick this would be to implement. With standard chutes, you have the "Safe to deploy?" field available on the part module, which is then accessible to kOS. It would be great to have the same functionality for RealChute.

Thanks!

**Comment by Petruchio96** [comment]
I remember reading on a post somewhere that you believe having the "Safe to deploy" status available is like cheating.  I don't necessarily disagree with that; however, I'm trying to run missions (landing unmanned probes) completely on KOS scripts with no piloting.  Your mod is a must for missions like that, but that feature is sorely missed.  If you're not interested in adding that, can you tell me what determines safe deployment so I can program it? (Is it just speed, dynamic pressure, aero heating, etc?)
