### ISSUE TITLE
Real chute causes game to crash when i load vehicle on VAB or SPH

### ISSUE THREAD

**Issue by JasonQ1232** [ChrisViral/RealChute#88]
I believe it to be an issue between Real Chutes and the StageRecovery mod the issue only occurs when I use a lot of chutes if I have the radial on max and start trying to place the chutes the game will start to chug.

**Comment by SkiRich** [comment]
I get the same issue, also with stagerecovery.  Placing more than one realchute parachute starts the process of very high cpu usage.  I recover all my stages so I use lots of parachutes, beyond 3 on one craft, on my system, makes the VAB unusable.  They work though, so technically things function fine, but the thread that is running in the VAB uses way too much CPU.  I know the author said no more dev on this version.  I await the new Realchute 2 but in the interrim, can you tweak the thread parameters  for this version for 1.9.1 of KSP?

**Comment by ChrisViral** [comment]
RealChute is only in maintaining mode now, I'm not particularly interested into fixing bugs coming from interactions with other mods. I suggest you enquire with whoever maintains StageRecovery, it sounds like the issue to fix would be on their end, not mine anyway.

Closing.
