### ISSUE TITLE
Parachutes not working

### ISSUE THREAD

**Issue by SBSmrt72** [ChrisViral/RealChute#91]
I have RO, FASA and all the dependancies for RO. The problem is that I can see the apollo cm parachutes in the vab, deployed. When launched, the parachutes are deployed. Is this a config error or something else?

Picture from VAB: https://gyazo.com/950f8a36a6b1f3c8d6192e81aeae241c

**Comment by Starwaster** [comment]
I use those same parts with RO + RC and I don't experience that behavior. Nor has anyone reported it in any RO channels that I'm aware of. And there's not enough information that you've provided to even guess as to why it's happening to you.
