### ISSUE TITLE
Chutes get cut too quickly, causing vessels to get damaged or destroyed.

### ISSUE THREAD

**Issue by linuxgurugamer** [ChrisViral/RealChute#93]
Take the attached vessel
and just launch straight up, it will come back down and land, and take a second or two before starting to fall over. 

[RealChuteTestCraft.zip](https://github.com/ChrisViral/RealChute/files/4842956/RealChuteTestCraft.zip)

PR I submitted seems to take care of the problem with a 1 or 2 second delay at most

An alternative might be to look at the CoM movement, but that too will have some issues

**Comment by ChrisViral** [comment]
Thanks a lot, I'll take a full look at it.

As mentioned in private I also want to see if I can find a way to tackle the weird aero in water cuts. Enough people have reported it that I need to take it seriously, but I still haven't figured out how to reproduce it locally, so I'll mess around with this when I can to figure it out.

**Comment by linuxgurugamer** [comment]
Sure thing, glad I could help.
Just thought of another idea.  I don't know how quickly the value changes, but maybe keep track of the last few, and if it changes too radically (ie:  from air into water), maybe use the old value?

**Comment by ChrisViral** [comment]
Could work, but that's also kind of curving around the issue and not fixing it. There's an inherent physics problem behind this and I want to tackle it if I can find the source.

**Comment by ChrisViral** [comment]
Fixed in newest update by simply checking for surface speed rather than just horiztonal speed, changes in 524bebd

**Comment by linuxgurugamer** [comment]
Thank you
