### ISSUE TITLE
Not working on KSP 1.11

### ISSUE THREAD

**Issue by grandma-uwu** [ChrisViral/RealChute#95]
When I try to start the game i am getting a incompatibility message. Game still loads but without the mod

**Comment by grandma-uwu** [comment]
I think this may occure because of new chute angle system, Squad added in this version

**Comment by davideagen** [comment]
Chutes also do not appear in the part picker.

**Comment by tonimark** [comment]
the same issue, I waited for an update, he said that he is developing real chute 2 so let's forget this mod for a while...

**Comment by ChrisViral** [comment]
As mentioned several times in the thread, it's disabled on purpose on new version. Wait for the updates and be patient. Closing.
