### ISSUE TITLE
RealChute 1.4.8.1 not (fully) compatible KSP 1.10.1 - CKAN entry say 1.8.0-1.11

### ISSUE THREAD

**Issue by TorbjornLindgren** [ChrisViral/RealChute#97]
FYI,
RealChute 1.4.8.1 causes KSP 1.10.1 (and probably all non 1.11.0 versions) to continuously scroll error messages in the KSP log (and visible via Alt-F12) while standing at the launch pad with a new vehicle (nothing fancy, just two parts I threw together). This happens even when there's no RealChute parts on the vehicle.

I believe it's also spams this message any time there's a vehicle active since I was in that situation when I first noticed it, though that had install had lots of other mods (but the same message argues it's the same root cause).

I've tested it with a completely stock 1.10.1 install and just installing RealChute via CKAN, this installs 1.4.8.1 (since it's marked as compatible with 1.10.1) and adds ModuleManager 4.1.4 due to dependency, this is what I used to create the attached logfile.

The logfile grows very quickly because the log message repeats multiple times per second. The logfile from the running instance when I first decided to find out which of the mods that made the log entries was 477 MB, 99.9+% was this one message.

Downgrading to RealChute 1.4.8 fixes the issue on 1.10.1, and 1.4.8.1 on KSP 1.11.0 is also fine so you could just ask CKAN to mark 1.4.8.1 for only 1.11 instead of 1.8.0-1.11 if it turns out to be not easy (or trivial) to fix,

You can check the log for context but the repeating messages looks like this:
[EXC 21:41:39.852] TypeLoadException: Could not resolve type with token 010000a1 (from typeref, class/assembly EditorLogicBase, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[KSP.log](https://github.com/ChrisViral/RealChute/files/5845279/KSP.log)

**Comment by ChrisViral** [comment]
Huh, that's odd, none of the code changed.
Gonna push a silent update changing the compatibility bounds.

**Comment by ChrisViral** [comment]
Done, I also flushed the tag, so that release cannot be downloaded anymore.
