### ISSUE TITLE
ckan not working

### ISSUE THREAD

**Issue by glilienthal** [ChrisViral/RealChute#98]
Ckan gives me the option to update to 1.4.8.1. This version is not found on github, yielding: 

Downloading "https://github.com/ChrisViral/RealChute/releases/download/v1.4.8.1/RealChute_v1.4.8.1.zip"
One or more downloads were unsuccessful:

Error downloading RealChute v1.4.8.1: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.

Maybe something wrong with the meta data? 

PS: Thanks a lot for the great mod.

**Comment by ChrisViral** [comment]
Because v1.4.8.1 had issues and it's been pulled off. Download 1.4.8.2 if on KSP 1.11, or stay on 1.4.8 if on earlier versions. That is all.

**Comment by glilienthal** [comment]
yep. Now 1.4.8.1. is gone from ckan. :)
